name: srnagent
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - cutadapt
  - fastqc
  - jupyter
  - ipykernel
  - samtools
  - viennarna=1.8.5
  - mirdeep2
  - subread
  - pysam
  - pip:
      - anndata
      - fastq-dl
      - tqdm
      - pylimma

