"""samtools idxstats quantification for small-RNA reference BAM files."""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Dict, List, Optional, Sequence

import numpy as np
import pandas as pd
from anndata import AnnData

from ..._registry import register_function
from ..._utils import run_cli_cmd, run_threads


def _resolve_bam_paths(adata: AnnData, bam_col: str) -> Dict[str, str]:
    if bam_col in adata.obs.columns:
        bam_paths = {
            str(sample): str(adata.obs.loc[sample, bam_col])
            for sample in adata.obs_names
            if str(adata.obs.loc[sample, bam_col]).strip()
        }
    elif "sam_path" in adata.obs.columns:
        bam_paths = {}
        for sample in adata.obs_names:
            sam = str(adata.obs.loc[sample, "sam_path"]).strip()
            if not sam:
                continue
            bam = str(Path(sam).with_suffix(".bam"))
            if Path(bam).exists():
                bam_paths[str(sample)] = bam
    else:
        raise KeyError(
            f"adata.obs must contain {bam_col!r}. Run sa.alignment.bowtie() "
            "against a small-RNA FASTA reference first."
        )

    missing = [
        f"{sample}: {path}"
        for sample, path in bam_paths.items()
        if not Path(path).exists()
    ]
    if missing:
        raise FileNotFoundError("BAM files not found: " + "; ".join(missing))
    if not bam_paths:
        raise ValueError("No BAM paths found in AnnData")
    return bam_paths


def _ensure_bam_index(bam: str, *, create_index: bool) -> None:
    path = Path(bam)
    bai_candidates = [Path(f"{bam}.bai"), path.with_suffix(".bai")]
    if any(candidate.exists() for candidate in bai_candidates):
        return
    if not create_index:
        return

    samtools = shutil.which("samtools") or "samtools"
    run_cli_cmd([samtools, "index", bam])


def _parse_idxstats_file(path: str | Path) -> pd.DataFrame:
    rows: List[tuple[str, int, float]] = []
    with open(path, encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.rstrip("\n")
            if not line.strip():
                continue
            fields = line.split("\t")
            if len(fields) < 4:
                raise ValueError(f"Invalid samtools idxstats row: {line}")
            ref_name = fields[0]
            rows.append((ref_name, int(fields[1]), float(fields[2])))

    return pd.DataFrame(rows, columns=["reference_name", "reference_length", "mapped_reads"])


@register_function(
    aliases=[
        "idxstats",
        "samtools_idxstats",
        "quantify_idxstats",
        "小RNAidxstats定量",
    ],
    category="quant",
    description=(
        "Quantify reads mapped to small-RNA FASTA reference sequences using "
        "samtools idxstats. This is intended for BAM files generated by "
        "aligning reads to a small-RNA FASTA index, not to a whole genome. "
        "The reference length column is written to adata.var and mapped read "
        "counts are written to adata.X and adata.layers['idxstats']."
    ),
    examples=[
        (
            'adata = sa.quant.idxstats(\n'
            '    adata,\n'
            '    bam_col="bam_path",\n'
            '    output_dir="idxstats_out",\n'
            ')'
        ),
    ],
    related=["alignment.bowtie"],
    produces={
        "obs": ["idxstats_bam", "idxstats_file"],
        "var": ["reference_name", "reference_length"],
        "layers": ["idxstats"],
        "uns": ["idxstats_result"],
    },
)
def idxstats(
    adata: AnnData,
    output_dir: str = "idxstats_out",
    *,
    bam_col: str = "bam_path",
    create_index: bool = True,
    drop_unmapped_reference: bool = True,
    jobs: Optional[int] = None,
    extra_args: Optional[Sequence[str]] = None,
) -> AnnData:
    """Run ``samtools idxstats`` over BAM files and return count AnnData.

    This method is for BAMs aligned against a small-RNA FASTA reference such as
    mature tRNA, miRNA, piRNA, or other transcript-level sequences. It is not a
    feature counter for whole-genome BAM files.
    """
    if extra_args:
        raise ValueError("samtools idxstats does not support extra arguments here")
    if not isinstance(adata, AnnData):
        raise TypeError("adata must be an AnnData object")

    out_dir = Path(output_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    samtools = shutil.which("samtools") or "samtools"

    bam_paths = _resolve_bam_paths(adata, bam_col)
    sample_names = [str(sample) for sample in adata.obs_names if str(sample) in bam_paths]

    def _process_sample(sample: str) -> tuple[str, pd.DataFrame, str]:
        bam = bam_paths[sample]
        _ensure_bam_index(bam, create_index=create_index)
        sample_out = out_dir / f"{sample}.idxstats.tsv"
        run_cli_cmd([
            "bash",
            "-lc",
            '"$1" idxstats "$2" > "$3"',
            "samtools_idxstats",
            samtools,
            bam,
            str(sample_out),
        ])
        frame = _parse_idxstats_file(sample_out)
        if drop_unmapped_reference:
            frame = frame[frame["reference_name"] != "*"].copy()
        return sample, frame, str(sample_out)

    results = run_threads(sample_names, _process_sample, jobs)
    sample_frames: Dict[str, pd.DataFrame] = {
        sample: frame for sample, frame, _ in results
    }
    output_files: Dict[str, str] = {
        sample: path for sample, _, path in results
    }

    references = list(sample_frames[sample_names[0]]["reference_name"])
    lengths = sample_frames[sample_names[0]].set_index("reference_name")["reference_length"]
    matrix = np.zeros((len(sample_names), len(references)), dtype=np.float64)

    for i, sample in enumerate(sample_names):
        frame = sample_frames[sample].set_index("reference_name")
        missing = [ref for ref in references if ref not in frame.index]
        if missing:
            raise ValueError(
                f"idxstats references differ for sample {sample}; missing: "
                + ", ".join(missing[:10])
            )
        matrix[i, :] = frame.loc[references, "mapped_reads"].to_numpy(dtype=np.float64)

    obs = adata.obs.loc[sample_names].copy()
    obs["idxstats_bam"] = [bam_paths[sample] for sample in sample_names]
    obs["idxstats_file"] = [output_files[sample] for sample in sample_names]

    var = pd.DataFrame(index=references)
    var["reference_name"] = references
    var["reference_length"] = [int(lengths.loc[ref]) for ref in references]

    quantified = AnnData(X=matrix, obs=obs, var=var)
    quantified.layers["idxstats"] = matrix.copy()
    quantified.uns.update(adata.uns)
    quantified.uns["idxstats_result"] = {
        "output_dir": str(out_dir),
        "bam_col": bam_col,
        "create_index": create_index,
        "drop_unmapped_reference": drop_unmapped_reference,
        "jobs": jobs,
        "files": output_files,
    }
    return quantified


samtools_idxstats = idxstats
