"""Dedicated JupyterLab process for the Overview page.

Isolated from Agent per-chat kernels. Root directory is the UI work_space.
"""

from __future__ import annotations

import atexit
import logging
import os
import secrets
import signal
import socket
import subprocess
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Optional

from work_space import get_work_space

logger = logging.getLogger(__name__)

DEFAULT_PORT = int(os.environ.get("UI_JUPYTERLAB_PORT", "8766"))

_lock = threading.RLock()
_proc: Optional[subprocess.Popen] = None
_port: int = DEFAULT_PORT
_token: str = ""
_bind_host: str = "0.0.0.0"
_started_at: float = 0.0
_log_path: Optional[Path] = None
_log_fh: Any = None
_atexit_registered = False


def _state_dir(workspace: Optional[Path] = None) -> Path:
    root = (workspace or get_work_space()).resolve()
    path = root / ".srnagent" / "jupyterlab"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _write_config(workspace: Path, *, port: int, token: str, bind_host: str) -> Path:
    state = _state_dir(workspace)
    runtime = state / "runtime"
    data = state / "data"
    config_dir = state / "config"
    for path in (runtime, data, config_dir):
        path.mkdir(parents=True, exist_ok=True)

    # Keep Lab's own files under .srnagent so the workspace tree stays clean.
    config_path = config_dir / "jupyter_server_config.py"
    # frame-ancestors * so Overview iframe works whether UI is localhost or LAN IP.
    config_path.write_text(
        "\n".join(
            [
                "# Auto-generated by sRNAgent UI — do not edit by hand.",
                f"c.ServerApp.root_dir = {str(workspace)!r}",
                f"c.ServerApp.preferred_dir = {str(workspace)!r}",
                f"c.ServerApp.ip = {bind_host!r}",
                f"c.ServerApp.port = {int(port)}",
                "c.ServerApp.open_browser = False",
                f"c.ServerApp.token = {token!r}",
                "c.ServerApp.password = ''",
                "c.ServerApp.allow_remote_access = True",
                "c.ServerApp.allow_origin = '*'",
                "c.ServerApp.disable_check_xsrf = True",
                f"c.ServerApp.runtime_dir = {str(runtime)!r}",
                f"c.ServerApp.data_dir = {str(data)!r}",
                "c.ServerApp.tornado_settings = {",
                "    'headers': {",
                "        'Content-Security-Policy': \"frame-ancestors *;\",",
                "        'X-Frame-Options': '',",
                "    }",
                "}",
                "c.ServerApp.default_url = '/lab'",
                "c.LabApp.default_url = '/lab'",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return config_dir


def _port_open(host: str, port: int) -> bool:
    probe_host = "127.0.0.1" if host in {"0.0.0.0", "::"} else host
    try:
        with socket.create_connection((probe_host, port), timeout=0.5):
            return True
    except OSError:
        return False


def _pick_port(preferred: int, bind_host: str) -> int:
    if not _port_open(bind_host, preferred):
        return preferred
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _lab_ready(port: int, token: str, timeout_sec: float = 45.0) -> bool:
    url = f"http://127.0.0.1:{port}/api/status?token={token}"
    deadline = time.time() + timeout_sec
    while time.time() < deadline:
        if _proc is not None and _proc.poll() is not None:
            return False
        try:
            with urllib.request.urlopen(url, timeout=1.5) as resp:
                if resp.status == 200:
                    return True
        except (urllib.error.URLError, TimeoutError, OSError):
            pass
        time.sleep(0.4)
    return False


def _register_atexit() -> None:
    global _atexit_registered
    if _atexit_registered:
        return
    atexit.register(stop_jupyterlab)
    _atexit_registered = True


def get_jupyterlab_status() -> dict[str, Any]:
    with _lock:
        alive = _proc is not None and _proc.poll() is None
        ready = bool(alive and _token and _lab_api_ok(_port, _token))
        workspace = str(get_work_space())
        return {
            "ok": True,
            "running": alive,
            "ready": ready,
            "port": _port if alive or _token else DEFAULT_PORT,
            "token": _token if alive else "",
            "bindHost": _bind_host,
            "workspace": workspace,
            "logPath": str(_log_path) if _log_path else "",
            "startedAt": _started_at if alive else 0,
            "pid": _proc.pid if alive and _proc is not None else None,
            "isolated": True,
            "note": "独立 JupyterLab：不与 Agent 会话内核共享；根目录为 work_space",
        }


def _lab_api_ok(port: int, token: str) -> bool:
    if not port or not token:
        return False
    url = f"http://127.0.0.1:{port}/api/status?token={token}"
    try:
        with urllib.request.urlopen(url, timeout=1.0) as resp:
            return resp.status == 200
    except (urllib.error.URLError, TimeoutError, OSError):
        return False


def start_jupyterlab(
    *,
    bind_host: Optional[str] = None,
    port: Optional[int] = None,
    force_restart: bool = False,
) -> dict[str, Any]:
    """Start (or reuse) the Overview JupyterLab process."""
    global _proc, _port, _token, _bind_host, _started_at, _log_path, _log_fh

    with _lock:
        workspace = get_work_space().resolve()
        host = (bind_host or os.environ.get("UI_JUPYTERLAB_HOST") or "0.0.0.0").strip() or "0.0.0.0"
        preferred = int(port or os.environ.get("UI_JUPYTERLAB_PORT") or DEFAULT_PORT)

        if _proc is not None and _proc.poll() is None and not force_restart:
            if _lab_api_ok(_port, _token):
                return get_jupyterlab_status()
            # Process alive but API not ready yet — wait a bit.
            if _lab_ready(_port, _token, timeout_sec=20.0):
                return get_jupyterlab_status()

        if force_restart or (_proc is not None and _proc.poll() is None):
            _stop_locked()

        chosen_port = _pick_port(preferred, host)
        token = secrets.token_urlsafe(24)
        config_dir = _write_config(workspace, port=chosen_port, token=token, bind_host=host)
        log_path = _state_dir(workspace) / "jupyterlab.log"
        _log_path = log_path

        env = os.environ.copy()
        env["JUPYTER_CONFIG_DIR"] = str(config_dir)
        # Avoid picking up unrelated user labextensions that break Lab boot.
        env.setdefault("JUPYTER_PREFER_ENV_PATH", "1")

        cmd = [
            "jupyter",
            "lab",
            f"--config={config_dir / 'jupyter_server_config.py'}",
            f"--port={chosen_port}",
            "--no-browser",
            f"--ServerApp.token={token}",
            f"--ServerApp.root_dir={workspace}",
        ]

        log_fh = open(log_path, "ab", buffering=0)  # noqa: SIM115
        _log_fh = log_fh
        try:
            proc = subprocess.Popen(
                cmd,
                cwd=str(workspace),
                env=env,
                stdout=log_fh,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
        except FileNotFoundError:
            try:
                log_fh.close()
            except OSError:
                pass
            _log_fh = None
            return {
                "ok": False,
                "error": "未找到 jupyter 命令。请在 srnagent 环境中安装 jupyterlab。",
                "running": False,
                "ready": False,
            }
        except Exception as exc:  # noqa: BLE001
            try:
                log_fh.close()
            except OSError:
                pass
            _log_fh = None
            return {
                "ok": False,
                "error": f"启动 JupyterLab 失败：{exc}",
                "running": False,
                "ready": False,
            }

        _proc = proc
        _port = chosen_port
        _token = token
        _bind_host = host
        _started_at = time.time()
        _register_atexit()

        ready = _lab_ready(chosen_port, token, timeout_sec=60.0)
        if not ready:
            exit_code = proc.poll()
            snippet = ""
            try:
                snippet = log_path.read_text(encoding="utf-8", errors="replace")[-2000:]
            except OSError:
                pass
            _stop_locked()
            return {
                "ok": False,
                "error": "JupyterLab 启动超时或进程退出",
                "exitCode": exit_code,
                "logTail": snippet,
                "logPath": str(log_path),
                "running": False,
                "ready": False,
            }

        status = get_jupyterlab_status()
        status["ok"] = True
        return status


def _stop_locked() -> None:
    global _proc, _token, _started_at, _log_fh
    proc = _proc
    _proc = None
    if proc is None:
        _token = ""
        _started_at = 0.0
        if _log_fh is not None:
            try:
                _log_fh.close()
            except OSError:
                pass
            _log_fh = None
        return
    try:
        if proc.poll() is None:
            try:
                os.killpg(proc.pid, signal.SIGTERM)
            except (ProcessLookupError, PermissionError, OSError):
                proc.terminate()
            try:
                proc.wait(timeout=8)
            except subprocess.TimeoutExpired:
                try:
                    os.killpg(proc.pid, signal.SIGKILL)
                except (ProcessLookupError, PermissionError, OSError):
                    proc.kill()
                proc.wait(timeout=3)
    finally:
        _token = ""
        _started_at = 0.0
        if _log_fh is not None:
            try:
                _log_fh.close()
            except OSError:
                pass
            _log_fh = None


def stop_jupyterlab() -> dict[str, Any]:
    with _lock:
        _stop_locked()
        return {"ok": True, "running": False, "ready": False}


def build_lab_url(hostname: str, *, path: str = "/lab") -> str:
    """Client-facing Lab URL using the browser hostname + Lab port/token."""
    status = get_jupyterlab_status()
    port = int(status.get("port") or DEFAULT_PORT)
    token = str(status.get("token") or "")
    host = (hostname or "127.0.0.1").strip() or "127.0.0.1"
    base = f"http://{host}:{port}{path}"
    if token:
        sep = "&" if "?" in base else "?"
        return f"{base}{sep}token={token}"
    return base
