name: Auto Sync All ThirdParty Skills
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Sync nature-figure folder
        run: |
          TMP_DIR=tmp_nature_skill
          TARGET=sRNAgent/skills/nature-figure
          
          # 清理旧临时目录
          rm -rf $TMP_DIR
          # 清理本地旧的目标文件夹
          rm -rf $TARGET
          
          # 稀疏克隆上游仓库，只拉取 skills/nature-figure
          git clone --depth 1 --filter=blob:none --sparse https://github.com/Yuan1z0825/nature-skills.git $TMP_DIR
          cd $TMP_DIR
          git sparse-checkout set skills/nature-figure
          git checkout main
          
          # 拷贝目标文件夹到你的项目
          cd ..
          mkdir -p sRNAgent/skills
          cp -r $TMP_DIR/skills/nature-figure $TARGET
          
          # 删除临时仓库
          rm -rf $TMP_DIR

      - name: Commit & push changes
        run: |
          git config --global user.name "Sync Bot"
          git config --global user.email "sync-bot@github.com"
          git add sRNAgent/skills/nature-figure
          git commit -m "Auto sync nature-figure upstream latest" || echo "No file changes"
          git push
