name: Auto Sync All ThirdParty Skills
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v5

      - name: Sync nature-figure
        run: |
          # 定义路径
          TMP=tmp_upstream
          DEST=sRNAgent/skills/nature-figure
          SRC=skills/nature-figure
          UPSTREAM_URL=https://github.com/Yuan1z0825/nature-skills.git

          # 清理临时目录和旧目标文件夹
          rm -rf "$TMP" "$DEST"
          mkdir -p sRNAgent/skills

          # 稀疏克隆只拉需要的文件夹
          git clone --depth 1 --sparse "$UPSTREAM_URL" "$TMP"
          cd "$TMP"
          git sparse-checkout set "$SRC"
          git checkout main
          cd ..

          # 复制文件夹到你的项目
          cp -r "$TMP/$SRC" "$DEST"

          # 删除临时仓库
          rm -rf "$TMP"

      - name: Commit and push
        run: |
          git config --global user.name "Sync Bot"
          git config --global user.email "sync-bot@github.com"
          git add sRNAgent/skills/nature-figure
          git commit -m "Auto sync latest nature-figure" || echo "No changes detected"
          git push
